print("Abhishek Maurya")
print("Abhishek Maurya")
# print("Abhishek Maurya")
# print("Abhishek Maurya")
# print("Abhishek Maurya")
# print("Abhishek Maurya")
# print("Abhishek Maurya")
# print("Abhishek Maurya")